### ISSUE TITLE
Update the framework to 3.3.6

### ISSUE THREAD

**Issue by firelad97** [getgrav/grav-theme-bootstrap#9]
The current version used for this theme is outdated. Should be updated to the latest version of the framework, 3.3.6.

**Comment by rhukster** [comment]
Actually the theme now relies on the `bootstrapper` plugin and this was with bootstrap version 3.3.5, but i've just updated it to 3.3.6 and rereleased that plugin as 1.3.1.

I'll remove the old references to bootstrap in this theme the next time its updated/released, but as of now, there's no rush because it's not used.

**Comment by flaviocopes** [comment]
Removed Bootstrap in develop
